[/Script/Engine.Engine]
; 玩法规则由策划数据驱动：Content/Design/level01_map.json

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=00C19552472FDFBA46491C9B506D3369
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/Maps/L_Level01.L_Level01
EditorStartupMap=/Game/Maps/L_Level01.L_Level01
GlobalDefaultGameMode=/Game/Blueprints/BP_TDGameMode.BP_TDGameMode_C

